[{"line":1,"elements":[{"start_timestamp":"2025-02-18T13:26:42.879Z","line":2,"name":"Failure while executing Cucumber","description":"","id":"failure;failure-while-executing-cucumber","type":"scenario","keyword":"Scenario","steps":[{"result":{"duration":0,"status":"passed"},"line":3,"name":"Cucumber failed while executing","match":{"arguments":[],"location":"io.cucumber.core.Failure.failure_while_executing_cucumber()"},"keyword":"When "},{"result":{"duration":0,"error_message":"io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in stepDefinations.LoginStep6.confirmMessageAsInput(java.lang.String) and stepDefinations.LoginSteps.confirmMessageAsInput(java.lang.String)\r\n\tat io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$3(CachingGlue.java:278)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:272)\r\n\tat io.cucumber.core.runner.Runner.runPickle(Runner.java:72)\r\n\tat io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.lambda$runTestCase$4(CucumberEngineExecutionContext.java:114)\r\n\tat io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)\r\n\tat io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)\r\n\tat io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)\r\n\tat io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.runTestCase(CucumberEngineExecutionContext.java:111)\r\n\tat io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:168)\r\n\tat io.cucumber.junit.platform.engine.NodeDescriptor$PickleDescriptor.execute(NodeDescriptor.java:90)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n","status":"failed"},"line":4,"name":"Cucumber will report this error:","match":{"arguments":[],"location":"io.cucumber.core.Failure.cucumber_reports_this_error()"},"keyword":"Then "}]}],"name":"Test run failed","description":"There were errors during the execution","id":"failure","keyword":"Feature","uri":"classpath:io/cucumber/core/failure.feature","tags":[]}]